// Styles Import
import styles from "@/styles/Home.module.css";

// Components Imports
import Head from "next/head";
import { Footer } from "../../components/Footer";
import { Inter } from "next/font/google";
import { Links } from "../../components/Links";
import { HeadLine } from "../../components/HeadLine";
import { PageTitle } from "../../components/PageTitle";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <HeadLine page="index" />
          <Footer />
        </div>
        <PageTitle title="Index" />

        <Links />
      </main>
    </>
  );
};

export default Home;
