// Components Imports
import Head from "next/head";
import { Main } from "../../components/Main/Main";
import { Header } from "../../components/Header/Header";

const Home = (props) => {
  return (
    <div>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Main page="index" title="Index" />
    </div>
  );
};

export default Home;
